In [1]:
import pandas as pd
import numpy as np

In [2]:
skill =  pd.read_csv('industry_dimension_skills.csv')
skill = skill.drop(columns=['Unnamed: 0','surrogate keys'])
display(skill)

,industry_name,top_skills
0,accounting,"['auditing', 'financial accounting', 'tax acco..."
1,animation,"['animation', 'graphic design', 'video', 'anim..."
2,architecture and planning,"['architecture', 'urban planning', 'interior d..."
3,arts and crafts,"['visual arts', 'art history', 'graphic design..."
4,automotive,"['automotive', 'negotiation', 'leadership', 'a..."
...,...,...
65,textiles,"['apparel', 'product development', 'negotiatio..."
66,translation and localization,"['translation', 'linguistics', 'editing', 'tra..."
67,venture capital and private equity,"['growth strategies', 'entrepreneurship', 'cap..."
68,veterinary,"['veterinary medicine', 'zoology', 'agricultur..."
69,writing and editing,"['editing', 'writing', 'social media', 'editin..."

In [3]:
industry =  pd.read_csv('Industry_dimension.csv')
industry = industry.drop(columns=['Unnamed: 0','surrogate keys'])
display(industry)

,isic_section_index,isic_section_name,industry_name,Industry_group_sk,Industry_group_name,industry_id,industry_migration_2015_mean,industry_migration_2015_median,industry_migration_2016_mean,industry_migration_2016_median,industry_migration_2017_mean,industry_migration_2017_median,industry_migration_2018_mean,industry_migration_2018_median,industry_migration_2019_mean,industry_migration_2019_median
0,j,information and communication,computer hardware,19.0,hardware and netwoking,3,41.293077,40.400,49.323846,38.630,76.588462,55.720,45.841538,43.630,64.031538,38.310
1,j,information and communication,computer software,8.0,software and it services,4,88.915238,52.270,79.935000,59.265,40.293095,8.995,42.529048,21.065,-13.520595,-12.415
2,j,information and communication,computer networking,19.0,hardware and netwoking,5,107.741053,88.030,135.490000,123.750,97.912105,117.210,96.998421,154.470,83.589474,76.850
3,j,information and communication,internet,8.0,software and it services,6,223.364110,149.680,182.963151,120.030,136.965342,68.990,88.467123,51.160,10.061233,-5.440
4,j,information and communication,telecommunications,19.0,hardware and netwoking,8,14.634615,2.405,-9.259615,10.850,-27.346827,-4.440,-23.251250,-4.190,-22.044519,-21.265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,c,manufacturing,railroad manufacture,10.0,manufacturing,62,53.596000,-6.680,61.236000,48.140,29.224000,33.280,6.764000,14.340,0.544000,10.130
109,o,public administration and defence; compulsory ...,legislative office,20.0,public administration,72,-19.380000,-19.380,-6.740000,-6.740,9.740000,9.740,-16.340000,-16.340,-1.270000,-1.270
110,r,"arts, entertainment and recreation",libraries,13.0,nonprofit,85,12.910000,12.910,15.980000,15.980,6.090000,6.090,4.020000,4.020,4.020000,4.020
111,h,transportation and storage,warehousing,15.0,transportation and logistics,93,-4.420000,-4.420,5.900000,5.900,11.110000,11.110,-1.600000,-1.600,-1.460000,-1.460
112,m,professional scientific and technical activities,nanotechnology,19.0,hardware and networking,114,39.930000,39.930,20.240000,20.240,50.170000,50.170,14.620000,14.620,20.840000,20.840

In [4]:
result = pd.merge(industry, skill, on='industry_name', how='left')
display(result)

,isic_section_index,isic_section_name,industry_name,Industry_group_sk,Industry_group_name,industry_id,industry_migration_2015_mean,industry_migration_2015_median,industry_migration_2016_mean,industry_migration_2016_median,industry_migration_2017_mean,industry_migration_2017_median,industry_migration_2018_mean,industry_migration_2018_median,industry_migration_2019_mean,industry_migration_2019_median,top_skills
0,j,information and communication,computer hardware,19.0,hardware and netwoking,3,41.293077,40.400,49.323846,38.630,76.588462,55.720,45.841538,43.630,64.031538,38.310,"['computer hardware', 'inside sales', 'technic..."
1,j,information and communication,computer software,8.0,software and it services,4,88.915238,52.270,79.935000,59.265,40.293095,8.995,42.529048,21.065,-13.520595,-12.415,"['web development', 'development tools', 'data..."
2,j,information and communication,computer networking,19.0,hardware and netwoking,5,107.741053,88.030,135.490000,123.750,97.912105,117.210,96.998421,154.470,83.589474,76.850,"['computer networking', 'telecommunications', ..."
3,j,information and communication,internet,8.0,software and it services,6,223.364110,149.680,182.963151,120.030,136.965342,68.990,88.467123,51.160,10.061233,-5.440,"['web development', 'social media', 'digital m..."
4,j,information and communication,telecommunications,19.0,hardware and netwoking,8,14.634615,2.405,-9.259615,10.850,-27.346827,-4.440,-23.251250,-4.190,-22.044519,-21.265,"['telecommunications', 'computer networking', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,c,manufacturing,railroad manufacture,10.0,manufacturing,62,53.596000,-6.680,61.236000,48.140,29.224000,33.280,6.764000,14.340,0.544000,10.130,NaN
109,o,public administration and defence; compulsory ...,legislative office,20.0,public administration,72,-19.380000,-19.380,-6.740000,-6.740,9.740000,9.740,-16.340000,-16.340,-1.270000,-1.270,NaN
110,r,"arts, entertainment and recreation",libraries,13.0,nonprofit,85,12.910000,12.910,15.980000,15.980,6.090000,6.090,4.020000,4.020,4.020000,4.020,NaN
111,h,transportation and storage,warehousing,15.0,transportation and logistics,93,-4.420000,-4.420,5.900000,5.900,11.110000,11.110,-1.600000,-1.600,-1.460000,-1.460,NaN
112,m,professional scientific and technical activities,nanotechnology,19.0,hardware and networking,114,39.930000,39.930,20.240000,20.240,50.170000,50.170,14.620000,14.620,20.840000,20.840,NaN

In [7]:
result['surrogate keys'] = range(1,len(result)+1)

In [12]:
display(result)

,isic_section_index,isic_section_name,industry_name,Industry_group_sk,Industry_group_name,industry_id,industry_migration_2015_mean,industry_migration_2015_median,industry_migration_2016_mean,industry_migration_2016_median,industry_migration_2017_mean,industry_migration_2017_median,industry_migration_2018_mean,industry_migration_2018_median,industry_migration_2019_mean,industry_migration_2019_median,surrogate keys
0,j,information and communication,computer hardware,19.0,hardware and netwoking,3,41.293077,40.400,49.323846,38.630,76.588462,55.720,45.841538,43.630,64.031538,38.310,1
1,j,information and communication,computer software,8.0,software and it services,4,88.915238,52.270,79.935000,59.265,40.293095,8.995,42.529048,21.065,-13.520595,-12.415,2
2,j,information and communication,computer networking,19.0,hardware and netwoking,5,107.741053,88.030,135.490000,123.750,97.912105,117.210,96.998421,154.470,83.589474,76.850,3
3,j,information and communication,internet,8.0,software and it services,6,223.364110,149.680,182.963151,120.030,136.965342,68.990,88.467123,51.160,10.061233,-5.440,4
4,j,information and communication,telecommunications,19.0,hardware and netwoking,8,14.634615,2.405,-9.259615,10.850,-27.346827,-4.440,-23.251250,-4.190,-22.044519,-21.265,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,c,manufacturing,railroad manufacture,10.0,manufacturing,62,53.596000,-6.680,61.236000,48.140,29.224000,33.280,6.764000,14.340,0.544000,10.130,109
109,o,public administration and defence; compulsory ...,legislative office,20.0,public administration,72,-19.380000,-19.380,-6.740000,-6.740,9.740000,9.740,-16.340000,-16.340,-1.270000,-1.270,110
110,r,"arts, entertainment and recreation",libraries,13.0,nonprofit,85,12.910000,12.910,15.980000,15.980,6.090000,6.090,4.020000,4.020,4.020000,4.020,111
111,h,transportation and storage,warehousing,15.0,transportation and logistics,93,-4.420000,-4.420,5.900000,5.900,11.110000,11.110,-1.600000,-1.600,-1.460000,-1.460,112
112,m,professional scientific and technical activities,nanotechnology,19.0,hardware and networking,114,39.930000,39.930,20.240000,20.240,50.170000,50.170,14.620000,14.620,20.840000,20.840,113

In [11]:
result= result.drop(columns=['top_skills'])

In [13]:
result.to_csv("Industry_dimension_final.csv")